In [1]:
import numpy as np
x = np.array([1, 2, 3])
x.__class__
x.shape
x.ndim

1

In [2]:
for i in range(1, 10):
    for j in range(1, 10):
        print("n = {}, m ={}, shape = {}, dim = {}".format(i, j, np.zeros((i, j)).shape, np.zeros((i, j)).ndim))

n = 1, m =1, shape = (1, 1), dim = 2
n = 1, m =2, shape = (1, 2), dim = 2
n = 1, m =3, shape = (1, 3), dim = 2
n = 1, m =4, shape = (1, 4), dim = 2
n = 1, m =5, shape = (1, 5), dim = 2
n = 1, m =6, shape = (1, 6), dim = 2
n = 1, m =7, shape = (1, 7), dim = 2
n = 1, m =8, shape = (1, 8), dim = 2
n = 1, m =9, shape = (1, 9), dim = 2
n = 2, m =1, shape = (2, 1), dim = 2
n = 2, m =2, shape = (2, 2), dim = 2
n = 2, m =3, shape = (2, 3), dim = 2
n = 2, m =4, shape = (2, 4), dim = 2
n = 2, m =5, shape = (2, 5), dim = 2
n = 2, m =6, shape = (2, 6), dim = 2
n = 2, m =7, shape = (2, 7), dim = 2
n = 2, m =8, shape = (2, 8), dim = 2
n = 2, m =9, shape = (2, 9), dim = 2
n = 3, m =1, shape = (3, 1), dim = 2
n = 3, m =2, shape = (3, 2), dim = 2
n = 3, m =3, shape = (3, 3), dim = 2
n = 3, m =4, shape = (3, 4), dim = 2
n = 3, m =5, shape = (3, 5), dim = 2
n = 3, m =6, shape = (3, 6), dim = 2
n = 3, m =7, shape = (3, 7), dim = 2
n = 3, m =8, shape = (3, 8), dim = 2
n = 3, m =9, shape = (3, 9), dim = 2
n

In [3]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
print(W + X)
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [6]:
import numpy as np
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.rand(10, 2)
h = np.dot(x, W1) + b1
print(h)

[[ 0.27541539 -0.336026   -1.25576558  0.2564792 ]
 [ 0.26260031 -0.06421673 -1.19809256  0.5003248 ]
 [ 0.30356128 -0.47017992 -1.34257918  0.02554555]
 [ 0.2980374  -0.68136632 -1.34599397 -0.08546245]
 [ 0.30872433 -0.99648107 -1.40170544 -0.34702655]
 [ 0.32755893 -1.30538034 -1.47866837 -0.64578953]
 [ 0.24396366 -0.82623973 -1.21387723  0.09321186]
 [ 0.34819466 -0.26597866 -1.44434384 -0.06623885]
 [ 0.24727266 -1.35232914 -1.26802756 -0.2698251 ]
 [ 0.27809643 -0.17715912 -1.24925445  0.34745744]]


In [7]:
np.random.randn(10, 2)

array([[-0.07979076,  0.27742698],
       [ 0.48608637, -1.20399814],
       [ 1.99022569, -1.29010583],
       [-0.01285124,  1.03274262],
       [ 1.80153354,  0.86738407],
       [-0.6728773 , -1.68665662],
       [ 0.20861714,  1.36281094],
       [ 0.99523242, -1.5688243 ],
       [-1.35619619, -0.33929871],
       [ 0.14127759,  1.92473684]])

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
a = sigmoid(h)

In [10]:
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
s = np.dot(a, W2) + b2
print(s)

[[ 1.16113591  2.03811574 -2.20710179]
 [ 1.28160939  2.19460109 -2.31881011]
 [ 1.04773243  1.92890778 -2.12365328]
 [ 0.98971638  1.8303261  -2.0561185 ]
 [ 0.86014184  1.66355161 -1.93577918]
 [ 0.72132536  1.50266826 -1.81694279]
 [ 1.07241149  1.83692469 -2.07463387]
 [ 1.00935365  1.9686752  -2.13992388]
 [ 0.89194176  1.59223884 -1.89775855]
 [ 1.20805865  2.11623515 -2.26046632]]


In [11]:
class Sigmoid:
    def __init__(self):
        self.params = []
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [13]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [14]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # Initialization of Weight and Bias
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        # Create Layers
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        # Substitute All Weight for "params"
        self.params = []
        for layer in self.layers:
            self.params += layer.params
        
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [15]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [16]:
s

array([[-1.53076009,  0.80190383,  0.61300782],
       [-1.93361113,  1.28827303,  0.72713383],
       [-1.55118535,  0.84670005,  0.55881799],
       [-2.08508701,  1.40430318,  0.61263773],
       [-2.01203748,  1.36574338,  0.64437692],
       [-1.39087679,  0.64466017,  0.53788026],
       [-2.07871383,  1.39071208,  0.57357971],
       [-1.81923535,  1.14404837,  0.71680504],
       [-2.04203769,  1.34067164,  0.47648365],
       [-2.02046525,  1.24997838,  0.32787494]])